### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/hire-job-fe#1]
Urgently fix error cannot login in your backend

![Screenshot (123)](https://github.com/IrhamNfrnda/hire-job-fe/assets/49361887/4c7fc36b-a828-4ecc-ba20-549ef7fc8e81)

**Comment by IrhamNfrnda** [comment]
Fixed, Login Success
![Opera Snapshot_2023-08-09_102840_hire-job-fe-theta vercel app](https://github.com/IrhamNfrnda/hire-job-web/assets/55636345/b5bd1ba8-0814-41f3-8508-36e48275a1f0)
