### ISSUE TITLE
Image strectch

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/hire-job-fe#2]
Fix image in your pendapat tentang mereka section 

from this

![Screenshot (125)](https://github.com/IrhamNfrnda/hire-job-fe/assets/49361887/92a8ba1c-1be5-4b88-9c7c-ea828fdbfd56)

to this, and add css object-fit and object-position in your image

![Screenshot (124)](https://github.com/IrhamNfrnda/hire-job-fe/assets/49361887/7c497081-702a-4ba2-8865-9e71bebfd9b6)

**Comment by AhmadNadeemJB** [comment]
Please Close this issue, its already fixed

**Comment by kubil-ismail** [comment]
<img width="1680" alt="Screenshot 2023-08-10 at 11 18 51" src="https://github.com/IrhamNfrnda/hire-job-web/assets/49361887/5f4c81b6-9425-4ff2-b8ce-2ab0517b5080">

Please fix change css property not object-cover: top but object-position: top
