### ISSUE TITLE
Please fix change css property not object-cover: top but object-position: top

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/hire-job-fe#3]
<img width="1680" alt="Screenshot 2023-08-10 at 11 18 51" src="https://github.com/IrhamNfrnda/hire-job-web/assets/49361887/5f4c81b6-9425-4ff2-b8ce-2ab0517b5080">

Please fix change css property not object-cover: top but object-position: top

_Originally posted by @kubil-ismail in https://github.com/IrhamNfrnda/hire-job-web/issues/2#issuecomment-1672530951_

**Comment by IrhamNfrnda** [comment]
Fixed

![Opera Snapshot_2023-08-11_103423_hire-job-fe-theta vercel app](https://github.com/IrhamNfrnda/hire-job-web/assets/55636345/f8c26aa9-ba14-4b79-af55-60fcb8d21728)
