### ISSUE TITLE
Minta tolong di cek ya ini ada register gagal tapi logonya sukses

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/hire-job-fe#4]
![Screenshot (177)](https://github.com/IrhamNfrnda/peworld-web/assets/49361887/44685d48-d93f-47e1-a62e-1b386e6119d8)

**Comment by kubil-ismail** [comment]
Issuenya karna emailnya sudah terdaftar

![Screenshot (178)](https://github.com/IrhamNfrnda/peworld-web/assets/49361887/433b4fe2-713d-4d62-a8dc-22c1ff5fec23)

**Comment by IrhamNfrnda** [comment]
Fixed

![asdasdasdasdasdasdasdasd](https://github.com/IrhamNfrnda/peworld-web/assets/55636345/88e06d5d-2ae0-4346-88c0-d5b759f99d3c)
