### ISSUE TITLE
Please fix in profile

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/hire-job-fe#5]
![Screenshot (179)](https://github.com/IrhamNfrnda/peworld-web/assets/49361887/7d8f3b6e-6764-4cde-8cec-88fa1c010f7b)

Minta tolong kalo di profile ketika datanya kosong jangan pake "-" tapi ganti yang lebih deskriptif seperti location not set, skill not set & position not set

**Comment by IrhamNfrnda** [comment]
Fixed

![profileee](https://github.com/IrhamNfrnda/peworld-web/assets/55636345/a10db1ec-4e55-40b9-b534-fc2849175fac)
