### ISSUE TITLE
Error on edit profile

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/hire-job-fe#6]
![Screenshot (180)](https://github.com/IrhamNfrnda/peworld-web/assets/49361887/272c594e-e906-4484-aae5-c77ecc560664)
![Screenshot (181)](https://github.com/IrhamNfrnda/peworld-web/assets/49361887/70e2c302-a6b4-400b-9eb3-f478a56b5650)

Ketika edit profile ada beberapa field yang wajib di isi makanya dapet error ini namun beri keterangan field apa yang perlu di isi dan tampilkan error yang deskriptif supaya user tidak bingung

**Comment by kubil-ismail** [comment]
![Screenshot (182)](https://github.com/IrhamNfrnda/peworld-web/assets/49361887/e6ea18f5-9387-4969-8805-9aae8a480d53)

Ketika update profile namun tidak mengisi skills dapet error ini

**Comment by kubil-ismail** [comment]
![Screenshot (183)](https://github.com/IrhamNfrnda/peworld-web/assets/49361887/07e802a2-43b8-4f4e-86b2-a4c5341b3ca8)

Sudah berhasil update profile namun data terbaru tidak masuk pada field disini harusnya ada deskripsi hallo test seperti di sidebar

**Comment by IrhamNfrnda** [comment]
Fixed

![Edit](https://github.com/IrhamNfrnda/peworld-web/assets/55636345/f8622074-bd9b-4403-8936-1ddfa153431c)

**Comment by kubil-ismail** [comment]
![Screenshot (220)](https://github.com/IrhamNfrnda/peworld-web/assets/49361887/b6bc395e-2c87-42a5-8916-64183bc36a93)

Untuk failed to update skills masih ada, flow dapet errornya masuk ke menu edit -> mengisi semua data kecuali deskripsi -> biarkan skills kosong -> submit. Maka akan ada error ini
