### ISSUE TITLE
Got error in job

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/hire-job-fe#7]
![Screenshot (185)](https://github.com/IrhamNfrnda/peworld-web/assets/49361887/0c82121f-01b3-4718-beca-6add8d34d484)
![Screenshot (184)](https://github.com/IrhamNfrnda/peworld-web/assets/49361887/3d7a471d-5860-45e1-974a-5e5a24d26ce0)

Format tanggal kamu salah nih, minta tolong placeholdernya di benerin ya jangan januari 2018

**Comment by kubil-ismail** [comment]
![Screenshot (186)](https://github.com/IrhamNfrnda/peworld-web/assets/49361887/6596a8d7-378b-4106-a4d7-80e7ab0e681b)

Ketika upload foto pada job pada network photo selalu null, minta tolong di cek ya

**Comment by IrhamNfrnda** [comment]
Fixed

![Job](https://github.com/IrhamNfrnda/peworld-web/assets/55636345/85dde3b3-a5fb-4f3f-8d43-bec05acc35f3)
